export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'
export const IS_ADMIN_LOGGED_IN_REQUEST = 'IS_ADMIN_LOGGED_IN_REQUEST'
export const IS_ADMIN_LOGGED_IN_SUCCESS = 'IS_ADMIN_LOGGED_IN_SUCCESS'
export const IS_ADMIN_LOGGED_IN_FAIL = 'IS_ADMIN_LOGGED_IN_FAIL'

